---
- name: Disks playbook
  hosts: dbservers
  become: yes

  tasks:
   - name: Create the Volume Group
     lvg:
      vg: RHCE
      pvs: /dev/xvdg

   - name: Create Logical Volume
     lvol:
      lv: AppDB2
      vg: RHCE
      size: 10G
      pvs: /dev/xvdg
      state: present
   - name: Format the disk
     filesystem:
      dev: /dev/RHCE/AppDB2
      fstype: xfs
   - name: Mount the disk
     mount:
      fstype: xfs
      src: /dev/RHCE/AppDB2
      state: mounted
      path: /mnt/appdb2
